# Generated by Django 5.0 on 2023-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailinfo',
            name='purpose',
            field=models.CharField(default='thanks', max_length=255),
            preserve_default=False,
        ),
    ]
